/*
 * Copyright (C) 2026 isXander
 * This file is part of Controlify.
 *
 * SPDX-License-Identifier: LGPL-3.0-or-later
 */
package dev.isxander.controlify.utils;

import com.mojang.blaze3d.platform.Window;

//? if >=26.3 {
import org.lwjgl.sdl.SDLMouse;
import org.lwjgl.system.MemoryStack;
import java.nio.FloatBuffer;
//?} else {
/*import org.lwjgl.glfw.GLFW;
*///?}

public final class CursorUtils {
	//? if >=26.3 {
	/// How close (in SDL window coordinates) a motion event must land to the last warp target
	/// to be considered the echo of that warp rather than real mouse movement.
	private static final float WARP_ECHO_TOLERANCE = 2.0f;
	/// How long after a warp its echo events may still arrive.
	private static final long WARP_ECHO_TIMEOUT_NANOS = 500_000_000L;

	private static boolean pendingWarp = false;
	private static float pendingWarpX, pendingWarpY;
	private static long pendingWarpTime;
	//?}

	private CursorUtils() {
	}

	public static void setVisibility(Window window, boolean visible) {
		//? if >=26.3 {
		if (visible) {
			SDLMouse.SDL_ShowCursor();
			SDLMouse.SDL_SetWindowRelativeMouseMode(window.handle(), false);
		} else {
			SDLMouse.SDL_HideCursor();
		}
		//?} else {
		/*GLFW.glfwSetInputMode(
			window.handle(),
			GLFW.GLFW_CURSOR,
			visible
				? GLFW.GLFW_CURSOR_NORMAL
				: GLFW.GLFW_CURSOR_HIDDEN
		);
		*///?}
	}

	public static void setPosition(Window window, float x, float y) {
		//? if >=26.3 {
		// SDL reports a warp outside relative mode as an ordinary mouse motion event (and never drops it
		// as a no-op, since the warp clears SDL's last known position). Remember where we warped so that
		// echo is not mistaken for the player touching the mouse. See isSyntheticWarpMotion.
		pendingWarp = true;
		pendingWarpX = x;
		pendingWarpY = y;
		pendingWarpTime = System.nanoTime();
		SDLMouse.SDL_WarpMouseInWindow(window.handle(), x, y);
		//?} else {
		/*GLFW.glfwSetCursorPos(window.handle(), x, y);
		*///?}
	}

	//? if >=26.3 {
	/// Returns true if the mouse motion event currently being dispatched was generated by our own
	/// {@link #setPosition} warp rather than by the player physically moving the mouse.
	/// Must be called on the thread that processes SDL events.
	public static boolean isSyntheticWarpMotion() {
		if (!pendingWarp) return false;

		if (System.nanoTime() - pendingWarpTime > WARP_ECHO_TIMEOUT_NANOS) {
			pendingWarp = false;
			return false;
		}

		float x, y;
		try (MemoryStack stack = MemoryStack.stackPush()) {
			FloatBuffer xBuf = stack.mallocFloat(1);
			FloatBuffer yBuf = stack.mallocFloat(1);
			SDLMouse.SDL_GetMouseState(xBuf, yBuf);
			x = xBuf.get(0);
			y = yBuf.get(0);
		}

		if (Math.abs(x - pendingWarpX) <= WARP_ECHO_TOLERANCE && Math.abs(y - pendingWarpY) <= WARP_ECHO_TOLERANCE) {
			// still sitting where we put it: this is the warp's echo (there may be more than one)
			return true;
		}

		// the cursor has moved away from where we put it, so this is real movement
		pendingWarp = false;
		return false;
	}
	//?}
}
